# Site settings
title: shincad's blog
motto: I think, therefore I am.
email: shincad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 신정욱의 기술 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shinzzan
github_username: shincad

# Build settings
markdown: kramdown

plugins: [jekyll-paginate]
paginate: 10


